# Generated by Django 3.1 on 2020-08-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='previous_work',
            new_name='work_experience',
        ),
    ]
